### ISSUE TITLE
環境構築時の環境変数について

### ISSUE THREAD

**Issue by take-cantik** [alterbooth/hol-todo-app-on-azure#6]
SECRET_KEYは公開してはいけないので
`docker-compose.yml`
にも追加するべきではないです。

なので、envファイルを作成する方法で設定を行うと良いです。

↓参考記事
https://docs.docker.jp/compose/environment-variables.html

↓該当箇所
<img width="1061" alt="スクリーンショット 2022-05-14 11 09 00" src="https://user-images.githubusercontent.com/50654077/168406955-6577ff1f-1b83-40b5-9c06-050f96cd60bb.png">

**Comment by takatoshiinaoka** [comment]
@take-cantik  ご指摘ありがとうございます。該当コードとそれに対応するページは修正しておきました。
